### ISSUE TITLE
Open API 3.0 support

### ISSUE THREAD

**Issue by bobby-brennan** [LucyBot-Inc/api-spec-converter#112]
Here's the spec:
https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md

Open API is shooting for a January launch.  Not worth investing too much effort before the spec is set in stone, but it seems reasonably stable if we want to make a first pass.

**Comment by MikeRalphson** [comment]
I'm happy to create a shim for [swagger2openapi](https://github.com/mermade/swagger2openapi) or were you thinking of making OpenAPI 3 the target for all the other conversions?

**Comment by bobby-brennan** [comment]
That would be great! Once that's done we should be able to handle
converting e.g. RAML to OpenAPI 3 by using swagger 2 as an intermediary.

On Mar 18, 2017 4:29 AM, "Mike Ralphson" <notifications@github.com> wrote:

I'm happy to create a shim for swagger2openapi
<https://github.com/mermade/swagger2openapi> or were you thinking of making
OpenAPI 3 the target for all the other conversions?

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/lucybot/api-spec-converter/issues/112#issuecomment-287525613>,
or mute the thread

**Comment by MikeRalphson** [comment]
Still needed: selection options in browser `index.html` and support for alphabetic ordering.

**Comment by bobby-brennan** [comment]
Added to web demo, and alpha ordering seems to be already supported.
