### ISSUE TITLE
UIFaces jpg URLs

### ISSUE THREAD

**Issue by sgustafsson** [LucyBot-Inc/api-spec-converter#114]
The file \dist\api-spec-converter.js contains over 1200 URLs to jpg images. 

module["exports"] = [
  "https://s3.amazonaws.com/uifaces/faces/twitter/jarjan/128.jpg",
  "https://s3.amazonaws.com/uifaces/faces/twitter/mahdif/128.jpg",
  "https://s3.amazonaws.com/uifaces/faces/twitter/sprayaga/128.jpg",
  "https://s3.amazonaws.com/uifaces/faces/twitter/ruzinav/128.jpg",
  "https://s3.amazonaws.com/uifaces/faces/twitter/Skyhartman/128.jpg",
  "https://s3.amazonaws.com/uifaces/faces/twitter/moscoz/128.jpg",
  "https://s3.amazonaws.com/uifaces/faces/twitter/kurafire/128.jpg",
  "https://s3.amazonaws.com/uifaces/faces/twitter/91bilal/128.jpg",
  "https://s3.amazonaws.com/uifaces/faces/twitter/igorgarybaldi/128.jpg",
....

They appear to be from the http://uifaces.com/ tool. 

Is this a specific subset of user images from uifaces.com? What are those images used for as part of api-spec-converter? The FAQ page at http://web.archive.org/web/20160511190737/http://uifaces.com/faq says the pictures can only be used for mockups.

**Comment by IvanGoncharov** [comment]
@sgustafsson those URLs used in `faker` and dependency chain look like this:
`api-spec-converter` => `sway` => `json-schema-faker` => `faker`.
We use `sway` only to validate Swagger 2.0 files and those URLs don't use in this props.
Hower `sway` also allow you to fake data based on JSON-Schema so it's legit usage.
The problem that we can't use part of `sway` lib, therefore, browserify build include it together with all dependencies.

**Comment by IvanGoncharov** [comment]
@sgustafsson In past I tried to split out Swagger 2.0 validation into separate lib but it stuck on Apigee side:
https://github.com/apigee-127/sway/issues/68

**Comment by sgustafsson** [comment]
OK, I see, thanks for the insights !

**Comment by bobby-brennan** [comment]
Closing this since it's coming from json-schema-faker. I don't think it's much of a worry for us outside of increasing the size of the dist file.
