### ISSUE TITLE
{"cause":{},"isOperational":true}

### ISSUE THREAD

**Issue by sajmmon** [LucyBot-Inc/api-spec-converter#115]
I get this when running api-spec-converter via https://lucybot.github.io/api-spec-converter/ for WADL file in: 
http://www.ebi.ac.uk/Tools/services/rest/ncbiblast?wadl

**Comment by bobby-brennan** [comment]
I've hit this issue before and it seems to be specific to the browser version.  If you are able to install the command-line version it seems to work fine:

```
npm i -g api-spec-converter
api-spec-converter http://www.ebi.ac.uk/Tools/services/rest/ncbiblast?wadl --from wadl --to swagger_2 > swagger.json
```

**Comment by bobby-brennan** [comment]
Seems to be working fine in the browser now.

**Comment by Simhadrivijaya** [comment]
{"cause":{},"isOperational":true} i got this error. How to solve this?

**Comment by bobby-brennan** [comment]
Do you have a link to the specification you're trying to convert?
