### ISSUE TITLE
Online version broken

### ISSUE THREAD

**Issue by MikeRalphson** [LucyBot-Inc/api-spec-converter#120]
Github.io link 404s for me.

**Comment by bobby-brennan** [comment]
Fixed, thanks!

**Comment by dtsao** [comment]
https://lucybot.github.io/api-spec-converter is giving 404's for me.

**Comment by bobby-brennan** [comment]
The page has moved after renaming the repo. Here's the new link:

https://lucybot-inc.github.io/api-spec-converter/

**Comment by dtsao** [comment]
Thanks very much. I was able to convert a raml file to swagger - great tool!
