### ISSUE TITLE
Downconverting OpenAPI 3.0.x to 2.0

### ISSUE THREAD

**Issue by MikeRalphson** [LucyBot-Inc/api-spec-converter#140]
There's a MIT-licensed converter [here](https://github.com/Orange-OpenSource/angular-swagger-ui/blob/master/src/scripts/modules/openapi3-converter.js).

* It's designed as an Angular module, but it looks easy to shim if necessary
* It may be a little simplistic / incomplete in terms of producing valid OpenAPI 2.0 output

**Comment by MikeRalphson** [comment]
A more complete option (when available) would be to use the Mulesoft converter to round-trip through RAML 1.0

**Comment by MikeRalphson** [comment]
The first option works better than I expected (i.e. the output given a Petstore in 3.0 is valid 2.0). If anyone wants to pick this up, an example of the shim code is here https://gist.github.com/MikeRalphson/a14643b0731699516d9f8743ac59e643

**Comment by bobby-brennan** [comment]
Here's a first pass: https://github.com/LucyBot-Inc/api-spec-converter/pull/141

I went the other route and just edited the Angular code you found above to make it more friendly. We wouldn't be able to pull in new changes, but it seems a bit safer.
