### ISSUE TITLE
Example conversion from WADL to swagger not working

### ISSUE THREAD

**Issue by joechicken** [LucyBot-Inc/api-spec-converter#146]
On the linked example https://lucybot-inc.github.io/api-spec-converter/ the WADL example doesn't work.

Specification URL

http://api.apigee.com/v1/consoles/facebook/apidescription?format=wadl
Examples
Source Format
WADL
Destination Format
Open API 2.0 (Swagger)
 Convert!
TypeError: Failed to fetch

Open an issue on GitHub

**Comment by bobby-brennan** [comment]
Thanks for the report, just needed to change http to https. Should be fixed now.
