### ISSUE TITLE
Size limit Attributes missing after conversion

### ISSUE THREAD

**Issue by harrychengchen** [LucyBot-Inc/api-spec-converter#157]
When converting from swagger 1 to swagger 2, if I have a size limit attribute such as maxItems or maxLength, like this: 

`{
        "type" : "array",
        "items" : {
          "$ref" : "Grade"
        },
        "uniqueItems" : true,
        "maxItems" : "13", //<------- This attribute
        "paramType" : "query",
        "name" : "grades"
      }`

It's missing from the result:
`"grades": {
          "items": {
            "$ref": "#/definitions/Grade"
          },
          "type": "array",
          "uniqueItems": true
        }`

**Comment by bobby-brennan** [comment]
Thanks for the report. I've opened a pull request in a downstream dependency:

https://github.com/apigee-127/swagger-converter/pull/79

**Comment by bobby-brennan** [comment]
This is fixed in 2.7.4
