### ISSUE TITLE
TypeError: Cannot read property '$ref' of undefined when transfer openapi v3 to swagger v2

### ISSUE THREAD

**Issue by nsw** [LucyBot-Inc/api-spec-converter#162]
when execute the command :  api-spec-converter openapi-swagger.json --from=openapi_3 --to=swagger_2 > swagger-v2.json
got an error
Fatal TypeError: Cannot read property '$ref' of undefined

**Comment by MikeRalphson** [comment]
Are you able to share your input document via a gist etc?

**Comment by nsw** [comment]
@MikeRalphson  something like :

schema:
     $ref: '#/components/schemas/User'

**Comment by MikeRalphson** [comment]
@nsw That's really not enough to go on. `$ref`s are handled by the converter ok.

**Comment by nsw** [comment]
@MikeRalphson For example, if I have a API apec which don't have an associated schema, it will generate this error: Fatal TypeError: Cannot read property '$ref' of undefined

{
    "info": {
        "title": "Nodejs",
        "version": "1.0.0"
    },
    "openapi": "3.0.0",
    "paths": {
        "/articles": {
            "get": {
                "operationId": "ArticleController.getAll",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {}
                        },
                        "description": "Successful response"
                    }
                },
                "summary": "Get all",
                "tags": [
                    "Article"
                ]
            }
        }
    }
}



Seems that this following kind of config is necessary ? otherwise it will cause en error...
 
schema:
$ref: '#/components/schemas/<SomeSchema>'

**Comment by nsw** [comment]
@MikeRalphson By the way i use version 2.7.6 ..

**Comment by bobby-brennan** [comment]
@nsw thanks for the minimal example, I was able to reproduce using that. Published a fix in 2.7.7

**Comment by nsw** [comment]
@bobby-brennan   Thanks for the quick fix ! Super efficient.  It works as expected now :) :)
