### ISSUE TITLE
Transitive inclusion of `should` mutating Object prototype

### ISSUE THREAD

**Issue by vaskevich** [LucyBot-Inc/api-spec-converter#182]
One issue with #139 is that v2.9.2 of `openapi-spec-converter` transitively includes the `should` package at runtime via `swagger2openapi`, which mutates the Object prototype and can cause runtime errors. This extends to this package.

I merged a fix to the offending package (https://github.com/Mermade/oas-kit/pull/83) but the issue is that it's on v3.2.10 now, and I think that needs some work for compatibility. In the meantime, I've just been using the following `resolutions` statement in my `package.json`:

    "api-spec-converter/swagger2openapi": "github:vaskevich/oas-kit#swagger2openapi-v2.9.2-gitpkg"

**Comment by bobby-brennan** [comment]
Thanks for tracking this down Mike.

Unfortunately browserify chokes on the latest `oas-validator` due to `tweetnacl` using `process.versions.node`. Working on a fix...

**Comment by vaskevich** [comment]
Hi @bobby-brennan, were you able to figure this out?

**Comment by bobby-brennan** [comment]
Funny, I was just [discussing this issue with Mike](https://github.com/Mermade/oas-kit/issues/122#issuecomment-451884529).

I haven't found a way to fix this, though I've chased it down to `better-ajv-errors`, specifically [this file](https://github.com/atlassian/better-ajv-errors/blob/a4a52574b238e9e38b03313178e5b8daae3db432/index.js#L3)

I do think moving to webpack would fix the issue, but I haven't had luck so far :/

**Comment by vaskevich** [comment]
Ok, I tried to take a stab at it real quick but wasn't sure how to validate. There's `--insert-global-vars` flag in browserify, but looking further it seems that it uses this process Package, which sets up an empty object for `process.versions`: https://github.com/defunctzombie/node-process/blob/master/browser.js#L160. It could be reasonable to add 'node' in there with a value corresponding to the active calling Node process version, if you wanted to go down a rabbit hole!

**Comment by MikeRalphson** [comment]
@bobby-brennan I've managed to re-create the fix as it would apply to `v2.9.2`, backported one other fix which showed up in testing and released a `v2.9.3`. I've removed `coveralls` as a `devDependency` which seems to completely remove `tweetnacl` from the `package-lock.json`. 

Hope this helps.

**Comment by MikeRalphson** [comment]
@bobby-brennan I've backported another fix regarding `links` and created `v2.9.4` as I needed this for APIs.guru. It would be great to get this dependency updated.

**Comment by bobby-brennan** [comment]
Sorry, which package is now at `2.9.4`?

**Comment by MikeRalphson** [comment]
`swagger2openapi` has a bugfix release on this branch.

**Comment by bobby-brennan** [comment]
OK, I just published `api-spec-converter@2.7.29` which uses `swagger2openapi@2.9.4`

To be sure - I didn't update `./lib/formats/openapi_3.js` to use `oas-validator`. Hopefully the issue is still fixed. 

@vaskevich can you confirm?

**Comment by MikeRalphson** [comment]
"2.9.*" should be safe and allow additional patch releases for api-spec-converter.

**Comment by bobby-brennan** [comment]
OK - pinned to `2.9.*` in `api-spec-converter@2.7.31` 

Thanks for the fix Mike!

**Comment by vaskevich** [comment]
This has now been resolved; closing. Thanks again!

**Comment by rbren** [comment]
I'm still seeing `{}`.should defined _but only in the browser tests_ when I pin to `2.9.4`

@vaskevich it looks like the [same thing occurred](https://travis-ci.org/LucyBot-Inc/api-spec-converter/builds/583859721?utm_source=github_status&utm_medium=notification) when you originally wrote the test.

Is object mutation also a problem in-browser?

**Comment by vaskevich** [comment]
Weird, maybe something else is setting it? Not sure.
