### ISSUE TITLE
Support openapi3.0 to swagger2.0 with `oneOf` feature?

### ISSUE THREAD

**Issue by YouHang** [LucyBot-Inc/api-spec-converter#183]
When I use `api-spec-converter --from=openapi_3 --to=swagger_2 --syntax json --order=alpha swagger.json > swagger2.0.json`, I found it cannot  change `oneOf`(only support in 3.0) to a swagger 2.0 suitable format.

**Comment by bobby-brennan** [comment]
Yes, downgrading to 2.0 will generally be lossy. There's nothing we can do for the lack of `oneOf` support in 2.0

**Comment by toddiuszho** [comment]
Can it please forcibly remove `oneOf` under a path parameter? When trying to create an **ApiConfig** (OAS 2.0) for GCP API Gateway, it rejects the operation because `oneOf` fails validation.

"Will generally be lossy", yes. But in this context, not lossy enough!
