### ISSUE TITLE
OpenAPI 3 -> OpenAPI 2 conversion, convert explode to collectionFormat

### ISSUE THREAD

**Issue by MichelTenVoorde** [LucyBot-Inc/api-spec-converter#185]
We're having some issues converting our OpenAPI 3 spec to OpenAPI 2.

The OpenAPI 2 **collectionFormat** has been replaced by **explode** in the OpenAPI 3 specification. It would be helpful if the converter would support this.

See:
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameter-object

**Comment by bobby-brennan** [comment]
This should be fixed in 2.7.13 - we're using the combination of `style` and `explode`  [seen here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#style-examples) to set `collectionFormat` - let me know if anything looks off

**Comment by MichelTenVoorde** [comment]
@bobby-brennan Thanks for the fix!
I think there are 2 remaining issues:
- the explode parameter ends up in the output as well, I think it should be deleted.
- an `explode = false` is only converted to `collectionFormat = csv` when there's a `style = form` as well. However, `style = form` is default for query parameters, so even when `style` is omitted, `explode` should be converted.

Thanks again!

**Comment by bobby-brennan** [comment]
Good catch - deleted both `explode` and `style`, and set the default `style` according to the spec. It will also only select `collectionFormat` if `type == 'array'` now
