### ISSUE TITLE
Converting an object without a URL

### ISSUE THREAD

**Issue by michaelyfan** [LucyBot-Inc/api-spec-converter#201]
On my server I have an openapi3.0 JSON string, received from the client, that I've parsed with `JSON.parse`. I'd like to convert this object to swagger2.0, but it seems that `api-spec-converter` only supports filepaths and URLs that lead to JSON files, and not JS objects or strings that represent JSON. Is there any way to do this in `api-spec-converter`? No other library I can find supports conversion in-memory.

**Comment by bobby-brennan** [comment]
Yes, I believe this is possible. You can see [index.js](https://github.com/LucyBot-Inc/api-spec-converter/blob/master/index.js) for usage

Something like this should work:
```js
var apisc = require('api-spec-converter')
var oai = new apisc.Formats.openapi_3()
oai.spec = {host: "http://example.com" /* etc */}
oai.convertTo('swagger_to').then(swagger2 => {
  console.log('swagger', swagger2.spec)
})
```

**Comment by bobby-brennan** [comment]
Sorry, this was incorrect. You can actually pass an object as `source` using the code in the README, but this is currently broken for oai3 -> swagger2. Closing this in favor of #202
