### ISSUE TITLE
Converters remove nulls from API definitions

### ISSUE THREAD

**Issue by MikeRalphson** [LucyBot-Inc/api-spec-converter#210]
This line looks like a bit of a blunt instrument:

https://github.com/LucyBot-Inc/api-spec-converter/blob/3298201c273436d22da6b0af9a7c3fd373f603ee/lib/util.js#L79

In the case of Swagger 2.0 and OpenAPI 3.x `null` values are allowed in examples and specification-extensions.

Is there a specific reason for their forced removal, or could any checking be moved back into the relevant formatters?

**Comment by bobby-brennan** [comment]
@IvanGoncharov implemented this I believe.  Removing `=== null` doesn't change any of the test cases. I'm all for removing.

**Comment by MikeRalphson** [comment]
Thanks, will raise a PR.
