### ISSUE TITLE
Converter somehow breaks process events / stacktracing

### ISSUE THREAD

**Issue by pedroscaff** [LucyBot-Inc/api-spec-converter#219]
I am using version `2.8.3` and, after requiring the module, somehow the events and error stack traces break. I can't listen to process events anymore and the stack trace is not there.

node version: `v12.6.0`

Steps to reproduce:

```javascript
const Converter = require('api-spec-converter');
process.on('exit', () => {
  console.log('exit');
});
throw new Error('error');
```

expected output:
```
exit
/path/to/script.js:40
throw new Error('error');
^

Error: error
    at Object.<anonymous> (/path/to/script.js:40:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
```

current:
```
/path/to/dir/node_modules/drafter.js/lib/drafter.nomem.js:1
((function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.drafter=f()}}))((function(){var module;var Module;if(!Module){Module={}}Module["ready"]=false;Module["log"]=(function(text){console.log("drafter.js: "+text)});Module["logErr"]=(function(text){console.error("drafter.js: "+text)});Module["onRuntimeInitialized"]=(function(){this.ready=true});var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["EN

Error: error
```

**Comment by pedroscaff** [comment]
if I use a wrapper function to convert, I can have it as a module and using `child_process.fork(...)` works correctly and doesn't break the process (since it is not the same process anymore).

**Comment by bobby-brennan** [comment]
Yeah, I've seen this before. I think this is an issue with the API blueprint parser. https://github.com/apiaryio/drafter-npm/issues/4

With the recent switch to optionalDependencies, you should be able to delete `node_modules/apib2swagger` (assuming you're not using API blueprint) to fix the issue.

**Comment by pedroscaff** [comment]
Thanks for the quick answer! I updated to `2.9.0` but still the same, the blueprint fails because `apib2swagger` is missing but the package that is causing the issue is `drafter.js`, and it is required before the `apib2swagger` in `lib/formats/api_blueprint.js` :(. Commenting out `require('drafter.js')`  fixes the bug / removing `drafter.js` as well. I couldn't find `drafter.js` being used anywhere else in the code, any chance it could be an optional dependency as well?

**Comment by bobby-brennan** [comment]
Yup, I think adding drafter as optional is perfectly fine, since it's only used by APIBP

**Comment by pedroscaff** [comment]
I am happy to do it, should I make a PR with this change?

**Comment by bobby-brennan** [comment]
That'd be great, thanks!
