### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by baoduy** [LucyBot-Inc/api-spec-converter#254]
Hi, This is a very useful tool and it is great if supporting typescript.

Thanks
Duy

**Comment by rbren** [comment]
That's a great idea. Happy to accept any PRs for ts support.

**Comment by francisizme** [comment]
@rbren , Do we have any guidance about contributions? Or just push a PR for you guys to check and merge?

**Comment by doppio** [comment]
@rbren Can this be reopened? I'd like to contribute a PR with TypeScript type definitions if you're still open to it.
