### ISSUE TITLE
online version https://lucybot-inc.github.io/api-spec-converter/ didn't work with error "TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by zhenfangwu** [LucyBot-Inc/api-spec-converter#257]
The online version at https://lucybot-inc.github.io/api-spec-converter/ didn't work with error "TypeError: Failed to fetch".
Here is the swagger json format:
{
  "openapi": "3.0.1",
  "info": {
    "title": "sample",
    "version": "v1"
  },
  "paths": {
    "/api/test": {
      "get": {... ... }
    }
  },,
  "components": {
    "schemas": {... ...}
  }
}

![image](https://user-images.githubusercontent.com/8452301/80140642-16d91680-855d-11ea-86dc-f5e9a33b432e.png)

**Comment by rbren** [comment]
Most likely you have CORS disabled for that URL. You should try the CLI tool.
