### ISSUE TITLE
Conversion from OpenAPI 3.0 to Swagger 2.0

### ISSUE THREAD

**Issue by lwu-gd-china** [LucyBot-Inc/api-spec-converter#258]
Hi, guys. Does this project support the conversion from OpenAPI 3.0 to Swagger 2.0? Too many tools only support Swagger 2.0 and we hope it can do it.

**Comment by rbren** [comment]
Yes, we can down-convert to 2.0. But be aware that the conversion is lossy - some things won't be converted.
