### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ac931274** [LucyBot-Inc/api-spec-converter#264]
I tried to convert the following URL and it failed with the above error.
https://foxhill.deskpro.com/api/docs

I have attached the file for ease of reference.
[docs.txt](https://github.com/LucyBot-Inc/api-spec-converter/files/4757842/docs.txt)

Any ideas why this failed?

**Comment by rbren** [comment]
Was this on the website?

Likely the URL has CORS enabled - if you use the CLI it should convert fine.

**Comment by rbren** [comment]
Closing due to lack of info
