### ISSUE TITLE
anyOf not resolving

### ISSUE THREAD

**Issue by lukepighetti** [LucyBot-Inc/api-spec-converter#294]
We have about 20 classes that are coming in with the AnyOf keyword as a prefix. The API spec is OpenAPI v3. I saw a commit here that looked like it was supposed to handle this. Is this expected behavior?

<img width="533" alt="Screen Shot 2021-02-18 at 9 34 02 PM" src="https://user-images.githubusercontent.com/666539/108449173-094df500-7231-11eb-95ce-8ec348485030.png">

**Comment by rbren** [comment]
I think you have the wrong project.

**Comment by lukepighetti** [comment]
Big mistake on my part, this was meant for a different repo.
