### ISSUE TITLE
Object.listFromJson

### ISSUE THREAD

**Issue by lukepighetti** [LucyBot-Inc/api-spec-converter#295]
The code generation is trying to access `Object.listFromJson` which is not a valid method. Spec is OpenAPI v3.

<img width="566" alt="Screen Shot 2021-02-18 at 9 35 15 PM" src="https://user-images.githubusercontent.com/666539/108449271-339fb280-7231-11eb-8f5a-498010e90629.png">

Is this the expected behavior?

**Comment by rbren** [comment]
I'm not sure where this code came from, but I don't think it was this project.

**Comment by lukepighetti** [comment]
Big mistake on my part, this was meant for a different repo.
